# Generated by Django 4.2.2 on 2023-07-20 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('club_name', models.CharField(max_length=100)),
                ('club_desc', models.TextField(null=True)),
                ('club_img', models.ImageField(upload_to='club')),
                ('teacher_cordinator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubElections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('voting', models.BooleanField(default=False)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='election', to='clubs.club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='clubs.club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='votedfor', to='clubs.clubelections')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='clubs.clubmember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=1000)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubchat', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubmem', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stdcand', to='clubs.clubmember')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='clubs.clubelections')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
