# Generated by Django 4.2.2 on 2023-07-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='is_cordinator',
            field=models.BooleanField(default=False),
        ),
    ]
