# Generated by Django 4.2.2 on 2023-07-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubmember_head_clubmember_is_cordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
