# Generated by Django 4.2.2 on 2023-07-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubmember_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votedfor', to='clubs.clubelections'),
        ),
    ]
